export const FETCH_SINGLE_PUPPY = 'FETCH_SINGLE_PUPPY';
export const FETCH_ALL_PUPPIES = 'FETCH_ALL_PUPPIES';

export const FETCH_SINGLE_KITTY = 'FETCH_SINGLE_KITTY';
export const FETCH_ALL_KITTIES = 'FETCH_ALL_KITTIES';
